// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYsfA1y8eLOpXmqfAeXD1zcBgCUyjxMyM',
    appId: '1:632918288126:web:de46791f6069dee9d6a7af',
    messagingSenderId: '632918288126',
    projectId: 'growth-management-33d8a',
    authDomain: 'growth-management-33d8a.firebaseapp.com',
    storageBucket: 'growth-management-33d8a.appspot.com',
    measurementId: 'G-M833FSE0Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBveKas1Boccw2oKrlhqDVfX2WNpJKsPjg',
    appId: '1:632918288126:android:e5753ae6bc22bc0ad6a7af',
    messagingSenderId: '632918288126',
    projectId: 'growth-management-33d8a',
    storageBucket: 'growth-management-33d8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA37z1UYR6JpQ7Y7zQFsXlkSApeLSwR3yE',
    appId: '1:632918288126:ios:ed5655f658d4ecded6a7af',
    messagingSenderId: '632918288126',
    projectId: 'growth-management-33d8a',
    storageBucket: 'growth-management-33d8a.appspot.com',
    androidClientId: '632918288126-c76ud1m9nacdk1r7l63brcegvcja69f3.apps.googleusercontent.com',
    iosClientId: '632918288126-n1trt7lfvglumnbarhim7d23snkj1mie.apps.googleusercontent.com',
    iosBundleId: 'com.example.growthManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA37z1UYR6JpQ7Y7zQFsXlkSApeLSwR3yE',
    appId: '1:632918288126:ios:ed5655f658d4ecded6a7af',
    messagingSenderId: '632918288126',
    projectId: 'growth-management-33d8a',
    storageBucket: 'growth-management-33d8a.appspot.com',
    androidClientId: '632918288126-c76ud1m9nacdk1r7l63brcegvcja69f3.apps.googleusercontent.com',
    iosClientId: '632918288126-n1trt7lfvglumnbarhim7d23snkj1mie.apps.googleusercontent.com',
    iosBundleId: 'com.example.growthManagement',
  );
}
